### PR TITLE
ssl support for websocket and http requests

### LINKED ISSUE #276: [Bug]: Moonraker with HTTPS doesn't work
### What happened and in what context?

I'm using Moonraker with HTTPS enabled.
When I set the server into https://127.0.0.1:7125 in the config file, the program think the "HTTPS" is the domain

### If needed, paste the relevant bot log contents here.

```

*******************************************************************
Current Moonraker telegram bot config
[bot]
server = https://127.0.0.1:7125/

[camera]
host = https://fluidd.*.*/webcam/stream

[progress_notification]
percent = 5
height = 5
time = 60


*******************************************************************
2023-06-07 17:19:57,933 - __main__ - ERROR - 

2023-06-07 17:19:59,140 - klippy - ERROR - HTTPConnectionPool(host='https', port=80): Max retries exceeded with url: //127.0.0.1:7125/printer/info (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0xffff7f683220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0xffff7f683220>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution
```

### If needed, paste the relevant bot journal contents here.

_No response_

### What branch does this occur on?

master

### Reports only on latest master or development branches!

- [X] I have updated to latest development/master version before submitting the bug

### PR DESCRIPTION
**Pull request by nlef**
Added ssl support

#273 
new configuration params in `[bot]` section:

- ssl: False by default
- ssl_validate: False by default
- port: 80 by default

### CODE REVIEW

**Comment by nlef** [comment]
@HinataKato
pls check this pr. SSL now should work correctly.

**Comment by HinataKato** [comment]
> @HinataKato pls check this pr. SSL now should work correctly.

Sorry for being this late, haven't had time lately

Looks like disabled certificates aren't working correctly? If ssl_validate=true, I get
>urllib3.connection - WARNING - Certificate did not match expected hostname blablabla

Seems pretty normal right? But when I set it to false, I get
>/moonraker-telegram-bot-env/lib/python3.11/site-packages/urllib3/connectionpool.py:1061: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
>websocket - ERROR - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: IP address mismatch, certificate is not valid for '127.0.0.1'. (_ssl.c:992) - goodbye

And the SSL part seems didn't work either. I set the server to my domain and got this
>websocket_helper - ERROR - Handshake status 502 Bad Gateway
>websocket - ERROR - Handshake status 502 Bad Gateway - goodbye
>websocket_helper - INFO - WebSocket closed

(My moonraker is working normally btw, I can access the info page for the SSL enabled port)

**Comment by nlef** [comment]
@HinataKato
I fixed errors related to certificate settings.
Please check again

**Comment by krawa** [comment]
```
Current Moonraker telegram bot config
[bot]
server = 192.168.0.107
port = 443
ssl = true
ssl_validate = false
user = kkkk
password = tkertdfgdfg
debug = true

2024-04-24 15:01:33,136 - apscheduler.scheduler - INFO - base.py:166 - Scheduler started
2024-04-24 15:01:33,138 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
2024-04-24 15:01:33,141 - apscheduler.scheduler - DEBUG - base.py:1016 - No jobs; waiting until a job is added
2024-04-24 15:01:34,151 - klippy - ERROR - klippy.py:154 - Unauthorized
2024-04-24 15:01:34,158 - apscheduler.scheduler - INFO - base.py:166 - Scheduler started
2024-04-24 15:01:34,163 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
2024-04-24 15:01:34,173 - apscheduler.scheduler - DEBUG - base.py:1016 - No jobs; waiting until a job is added
2024-04-24 15:01:34,539 - klippy - DEBUG - klippy.py:249 - JWT token expired, refreshing...
2024-04-24 15:01:34,958 - klippy - ERROR - klippy.py:253 - Unauthorized
2024-04-24 15:01:36,033 - klippy - DEBUG - klippy.py:249 - JWT token expired, refreshing...
2024-04-24 15:01:36,442 - klippy - ERROR - klippy.py:253 - Unauthorized
2024-04-24 15:01:36,448 - klippy - WARNING - klippy.py:485 - Failed adding announcements bot feed.

Unauthorized
2024-04-24 15:01:37,146 - apscheduler.scheduler - INFO - base.py:881 - Added job "WebSocketHelper.reshedule" to job store "default"
2024-04-24 15:01:37,149 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
2024-04-24 15:01:37,153 - apscheduler.scheduler - DEBUG - base.py:1019 - Next wakeup is due at 2024-04-24 15:01:39.144630+03:00 (in 1.992009 seconds)
2024-04-24 15:01:37,183 - websocket_helper - ERROR - websocket_helper.py:80 - Handshake status 401 Unauthorized -+-+- {'server': 'nginx/1.22.1', 'date': 'Wed, 24 Apr 2024 12:01:37 GMT', 'content-type': 'text/html', 'content-length': '179', 'connection': 'keep-alive', 'www-authenticate': 'Basic realm="Go away!"'} -+-+- b'<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n'
2024-04-24 15:01:37,185 - websocket_helper - INFO - websocket_helper.py:73 - WebSocket closed
2024-04-24 15:01:37,187 - __main__ - INFO - main.py:1221 - Exiting! Moonraker connection lost!
2024-04-24 15:01:37,189 - apscheduler.scheduler - INFO - base.py:198 - Scheduler has been shut down
```

**Comment by krawa** [comment]
> ```
> Current Moonraker telegram bot config
> [bot]
> server = 192.168.0.107
> port = 443
> ssl = true
> ssl_validate = false
> user = kkkk
> password = tkertdfgdfg
> debug = true
> 
> 2024-04-24 15:01:33,136 - apscheduler.scheduler - INFO - base.py:166 - Scheduler started
> 2024-04-24 15:01:33,138 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
> 2024-04-24 15:01:33,141 - apscheduler.scheduler - DEBUG - base.py:1016 - No jobs; waiting until a job is added
> 2024-04-24 15:01:34,151 - klippy - ERROR - klippy.py:154 - Unauthorized
> 2024-04-24 15:01:34,158 - apscheduler.scheduler - INFO - base.py:166 - Scheduler started
> 2024-04-24 15:01:34,163 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
> 2024-04-24 15:01:34,173 - apscheduler.scheduler - DEBUG - base.py:1016 - No jobs; waiting until a job is added
> 2024-04-24 15:01:34,539 - klippy - DEBUG - klippy.py:249 - JWT token expired, refreshing...
> 2024-04-24 15:01:34,958 - klippy - ERROR - klippy.py:253 - Unauthorized
> 2024-04-24 15:01:36,033 - klippy - DEBUG - klippy.py:249 - JWT token expired, refreshing...
> 2024-04-24 15:01:36,442 - klippy - ERROR - klippy.py:253 - Unauthorized
> 2024-04-24 15:01:36,448 - klippy - WARNING - klippy.py:485 - Failed adding announcements bot feed.
> 
> Unauthorized
> 2024-04-24 15:01:37,146 - apscheduler.scheduler - INFO - base.py:881 - Added job "WebSocketHelper.reshedule" to job store "default"
> 2024-04-24 15:01:37,149 - apscheduler.scheduler - DEBUG - base.py:940 - Looking for jobs to run
> 2024-04-24 15:01:37,153 - apscheduler.scheduler - DEBUG - base.py:1019 - Next wakeup is due at 2024-04-24 15:01:39.144630+03:00 (in 1.992009 seconds)
> 2024-04-24 15:01:37,183 - websocket_helper - ERROR - websocket_helper.py:80 - Handshake status 401 Unauthorized -+-+- {'server': 'nginx/1.22.1', 'date': 'Wed, 24 Apr 2024 12:01:37 GMT', 'content-type': 'text/html', 'content-length': '179', 'connection': 'keep-alive', 'www-authenticate': 'Basic realm="Go away!"'} -+-+- b'<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body>\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.22.1</center>\r\n</body>\r\n</html>\r\n'
> 2024-04-24 15:01:37,185 - websocket_helper - INFO - websocket_helper.py:73 - WebSocket closed
> 2024-04-24 15:01:37,187 - __main__ - INFO - main.py:1221 - Exiting! Moonraker connection lost!
> 2024-04-24 15:01:37,189 - apscheduler.scheduler - INFO - base.py:198 - Scheduler has been shut down
> ```

Error due to nginx authorization
With a different config, the bot connects to the Moonraker but cannot connect to WebSocket. There need to specify the authorization header

```
Current Moonraker telegram bot config
[bot]
server = user:password@192.168.0.107
api_token: 5f551389d9c94627ab9c
port = 443
ssl = true
ssl_validate = false
debug = true
```

**Comment by nlef** [comment]
@krawa 
nginx authorization together with moonraker authorization is not supported at the moment.
If there is a need for this (although I don't really understand why there are two authorization options at the same time), then please create a separate ticket.
I made a minor fix in parsing json which could lead to problems with authorization.

**Pull request merged**
